/**
 * @fileoverview Database type definitions generated from schema.md
 * 
 * This file is auto-generated by scripts/generate-typedef.js
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * To regenerate: npm run generate-typedef
 * 
 * Generated on: 2026-01-19T09:05:02.062Z
 */

/**
 * @typedef {Object} AccessLogs
 * @property {string} id - Primary key
 * @property {string} entry_type
 * @property {string} [notes]
 * @property {boolean} [notification_sent]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} qr_code_id - Foreign key to qr_codes.id
 * @property {string} scanned_by
 * @property {string} [timestamp]
 */

/**
 * @typedef {Object} ChatConversations
 * @property {string} id - Primary key
 * @property {string} [archived_at]
 * @property {string} [archived_by]
 * @property {string} [created_at]
 * @property {string} [last_message_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} [role_id] - Foreign key to organization_roles.id
 * @property {string} [status]
 * @property {string} [updated_at]
 * @property {string} user1_id
 * @property {string} [user2_id]
 */

/**
 * @typedef {Object} ChatMessages
 * @property {string} id - Primary key
 * @property {string} content
 * @property {string} conversation_id - Foreign key to chat_conversations.id
 * @property {string} [created_at]
 * @property {boolean} [is_read]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} [recipient_id]
 * @property {string} sender_id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} FeatureFlags
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} name
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} GeneralInviteLinks
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} created_by
 * @property {string} [expires_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} organization_role_id - Foreign key to organization_roles.id
 * @property {boolean} requires_approval
 * @property {string} token
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} Notifications
 * @property {string} id - Primary key
 * @property {string} [access_log_id] - Foreign key to access_logs.id
 * @property {string} [created_at]
 * @property {string} from_user_id
 * @property {boolean} [is_read]
 * @property {string} message
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} [qr_code_id] - Foreign key to qr_codes.id
 * @property {string} to_user_id
 * @property {string} type
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} OrganizationChatSettings
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} OrganizationInvitations
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} email
 * @property {string} expires_at
 * @property {string} first_name
 * @property {string} [general_invite_link_id] - Foreign key to general_invite_links.id
 * @property {string} invited_by
 * @property {string} last_name
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} organization_role_id - Foreign key to organization_roles.id
 * @property {number} [seat_type_id] - Foreign key to seat_types.id
 * @property {string} [status]
 * @property {string} token
 * @property {string} [updated_at]
 * @property {string} [user_id]
 */

/**
 * @typedef {Object} OrganizationMembers
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} [invited_by]
 * @property {string} [joined_at]
 * @property {string} [last_assigned_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} organization_role_id - Foreign key to organization_roles.id
 * @property {string} [seat_id] - Foreign key to seats.id
 * @property {string} [updated_at]
 * @property {string} user_id
 */

/**
 * @typedef {Object} OrganizationRoles
 * @property {number} id - Primary key
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} name
 * @property {number} organization_type_id - Foreign key to organization_types.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} OrganizationSeatTypeSettings
 * @property {string} organization_id - Primary key
 * @property {number} seat_type_id - Primary key
 * @property {boolean} [is_active]
 */

/**
 * @typedef {Object} OrganizationTypes
 * @property {number} id - Primary key
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} name
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} Organizations
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} created_by
 * @property {string} name
 * @property {number} organization_type_id - Foreign key to organization_types.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} Permissions
 * @property {string} id - Primary key
 * @property {string} code
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} name
 */

/**
 * @typedef {Object} Profiles
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} date_of_birth
 * @property {string} first_name
 * @property {string} last_name
 * @property {string} [main_organization_id] - Foreign key to organizations.id
 * @property {string} role_id - Foreign key to roles.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} QrCodes
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} created_by
 * @property {string} [document_photo_url]
 * @property {string} expires_at
 * @property {string} [identifier]
 * @property {boolean} [is_used]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} [status]
 * @property {string} token
 * @property {string} [updated_at]
 * @property {string} [validated_at]
 * @property {string} [validated_by]
 * @property {string} [visitor_id]
 * @property {string} [visitor_name]
 */

/**
 * @typedef {Object} RoleChatPermissions
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} recipient_role_id - Foreign key to organization_roles.id
 * @property {number} sender_role_id - Foreign key to organization_roles.id
 */

/**
 * @typedef {Object} RoleChatRolePermissions
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} recipient_role_id - Foreign key to organization_roles.id
 * @property {number} sender_role_id - Foreign key to organization_roles.id
 */

/**
 * @typedef {Object} Roles
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} [description]
 * @property {string} name
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} SeatAssignmentHistory
 * @property {string} id - Primary key
 * @property {string} [assigned_at]
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {string} seat_id - Foreign key to seats.id
 * @property {string} [unassigned_at]
 * @property {string} user_id
 */

/**
 * @typedef {Object} SeatPackages
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {string} [expires_at]
 * @property {string} name
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} seat_count
 * @property {string} [status]
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} SeatTypePermissions
 * @property {string} permission_id - Primary key
 * @property {number} seat_type_id - Primary key
 */

/**
 * @typedef {Object} SeatTypes
 * @property {number} id - Primary key
 * @property {string} [created_at]
 * @property {number} [default_capacity]
 * @property {string} [description]
 * @property {boolean} [is_chargeable]
 * @property {boolean} [is_system_type]
 * @property {string} name
 * @property {number} [organization_type_id] - Foreign key to organization_types.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} Seats
 * @property {string} id - Primary key
 * @property {number} capacity
 * @property {string} [created_at]
 * @property {boolean} [is_active]
 * @property {string} name
 * @property {string} organization_id - Foreign key to organizations.id
 * @property {number} seat_type_id - Foreign key to seat_types.id
 * @property {string} [updated_at]
 */

/**
 * @typedef {Object} UserFlags
 * @property {string} id - Primary key
 * @property {string} [created_at]
 * @property {boolean} enabled
 * @property {string} feature_flag_id - Foreign key to feature_flags.id
 * @property {string} [updated_at]
 * @property {string} user_id
 */

